/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as authLayoutImport } from './routes/(auth)/_layout';
import { Route as appLayoutImport } from './routes/(app)/_layout';
import { Route as appLayoutIndexImport } from './routes/(app)/_layout.index';
import { Route as authLayoutSigninImport } from './routes/(auth)/_layout.signin';
import { Route as appLayoutVineyardsImport } from './routes/(app)/_layout.vineyards';
import { Route as appLayoutLicensesImport } from './routes/(app)/_layout.licenses';
import { Route as appLayoutInvoicingImport } from './routes/(app)/_layout.invoicing';
import { Route as appLayoutHarvestsImport } from './routes/(app)/_layout.harvests';
import { Route as appLayoutCertificationsImport } from './routes/(app)/_layout.certifications';
import { Route as appLayoutCellarImport } from './routes/(app)/_layout.cellar';
import { Route as appLayoutAnalysisImport } from './routes/(app)/_layout.analysis';
import { Route as appLayoutVineyardsVineyardIdImport } from './routes/(app)/_layout.vineyards_.$vineyardId';

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')();
const appImport = createFileRoute('/(app)')();

// Create/Update Routes

const authRoute = authImport.update({
    id: '/(auth)',
    path: '/',
    getParentRoute: () => rootRoute,
} as any);

const appRoute = appImport.update({
    id: '/(app)',
    getParentRoute: () => rootRoute,
} as any);

const authLayoutRoute = authLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => authRoute,
} as any);

const appLayoutRoute = appLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => appRoute,
} as any);

const appLayoutIndexRoute = appLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutRoute,
} as any);

const authLayoutSigninRoute = authLayoutSigninImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => authLayoutRoute,
} as any);

const appLayoutVineyardsRoute = appLayoutVineyardsImport.update({
    id: '/vineyards',
    path: '/vineyards',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutLicensesRoute = appLayoutLicensesImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutInvoicingRoute = appLayoutInvoicingImport.update({
    id: '/invoicing',
    path: '/invoicing',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutHarvestsRoute = appLayoutHarvestsImport.update({
    id: '/harvests',
    path: '/harvests',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutCertificationsRoute = appLayoutCertificationsImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutCellarRoute = appLayoutCellarImport.update({
    id: '/cellar',
    path: '/cellar',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutAnalysisRoute = appLayoutAnalysisImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => appLayoutRoute,
} as any);

const appLayoutVineyardsVineyardIdRoute = appLayoutVineyardsVineyardIdImport.update({
    id: '/vineyards_/$vineyardId',
    path: '/vineyards/$vineyardId',
    getParentRoute: () => appLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/(app)': {
            id: '/(app)';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof appImport;
            parentRoute: typeof rootRoute;
        };
        '/(app)/_layout': {
            id: '/(app)/_layout';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof appLayoutImport;
            parentRoute: typeof appRoute;
        };
        '/(auth)': {
            id: '/(auth)';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof authImport;
            parentRoute: typeof rootRoute;
        };
        '/(auth)/_layout': {
            id: '/(auth)/_layout';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof authLayoutImport;
            parentRoute: typeof authRoute;
        };
        '/(app)/_layout/analysis': {
            id: '/(app)/_layout/analysis';
            path: '/analysis';
            fullPath: '/analysis';
            preLoaderRoute: typeof appLayoutAnalysisImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/cellar': {
            id: '/(app)/_layout/cellar';
            path: '/cellar';
            fullPath: '/cellar';
            preLoaderRoute: typeof appLayoutCellarImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/certifications': {
            id: '/(app)/_layout/certifications';
            path: '/certifications';
            fullPath: '/certifications';
            preLoaderRoute: typeof appLayoutCertificationsImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/harvests': {
            id: '/(app)/_layout/harvests';
            path: '/harvests';
            fullPath: '/harvests';
            preLoaderRoute: typeof appLayoutHarvestsImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/invoicing': {
            id: '/(app)/_layout/invoicing';
            path: '/invoicing';
            fullPath: '/invoicing';
            preLoaderRoute: typeof appLayoutInvoicingImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/licenses': {
            id: '/(app)/_layout/licenses';
            path: '/licenses';
            fullPath: '/licenses';
            preLoaderRoute: typeof appLayoutLicensesImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/vineyards': {
            id: '/(app)/_layout/vineyards';
            path: '/vineyards';
            fullPath: '/vineyards';
            preLoaderRoute: typeof appLayoutVineyardsImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(auth)/_layout/signin': {
            id: '/(auth)/_layout/signin';
            path: '/signin';
            fullPath: '/signin';
            preLoaderRoute: typeof authLayoutSigninImport;
            parentRoute: typeof authLayoutImport;
        };
        '/(app)/_layout/': {
            id: '/(app)/_layout/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof appLayoutIndexImport;
            parentRoute: typeof appLayoutImport;
        };
        '/(app)/_layout/vineyards_/$vineyardId': {
            id: '/(app)/_layout/vineyards_/$vineyardId';
            path: '/vineyards/$vineyardId';
            fullPath: '/vineyards/$vineyardId';
            preLoaderRoute: typeof appLayoutVineyardsVineyardIdImport;
            parentRoute: typeof appLayoutImport;
        };
    }
}

// Create and export the route tree

interface appLayoutRouteChildren {
    appLayoutAnalysisRoute: typeof appLayoutAnalysisRoute;
    appLayoutCellarRoute: typeof appLayoutCellarRoute;
    appLayoutCertificationsRoute: typeof appLayoutCertificationsRoute;
    appLayoutHarvestsRoute: typeof appLayoutHarvestsRoute;
    appLayoutInvoicingRoute: typeof appLayoutInvoicingRoute;
    appLayoutLicensesRoute: typeof appLayoutLicensesRoute;
    appLayoutVineyardsRoute: typeof appLayoutVineyardsRoute;
    appLayoutIndexRoute: typeof appLayoutIndexRoute;
    appLayoutVineyardsVineyardIdRoute: typeof appLayoutVineyardsVineyardIdRoute;
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
    appLayoutAnalysisRoute: appLayoutAnalysisRoute,
    appLayoutCellarRoute: appLayoutCellarRoute,
    appLayoutCertificationsRoute: appLayoutCertificationsRoute,
    appLayoutHarvestsRoute: appLayoutHarvestsRoute,
    appLayoutInvoicingRoute: appLayoutInvoicingRoute,
    appLayoutLicensesRoute: appLayoutLicensesRoute,
    appLayoutVineyardsRoute: appLayoutVineyardsRoute,
    appLayoutIndexRoute: appLayoutIndexRoute,
    appLayoutVineyardsVineyardIdRoute: appLayoutVineyardsVineyardIdRoute,
};

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(appLayoutRouteChildren);

interface appRouteChildren {
    appLayoutRoute: typeof appLayoutRouteWithChildren;
}

const appRouteChildren: appRouteChildren = {
    appLayoutRoute: appLayoutRouteWithChildren,
};

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren);

interface authLayoutRouteChildren {
    authLayoutSigninRoute: typeof authLayoutSigninRoute;
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
    authLayoutSigninRoute: authLayoutSigninRoute,
};

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(authLayoutRouteChildren);

interface authRouteChildren {
    authLayoutRoute: typeof authLayoutRouteWithChildren;
}

const authRouteChildren: authRouteChildren = {
    authLayoutRoute: authLayoutRouteWithChildren,
};

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren);

export interface FileRoutesByFullPath {
    '/': typeof appLayoutIndexRoute;
    '/analysis': typeof appLayoutAnalysisRoute;
    '/cellar': typeof appLayoutCellarRoute;
    '/certifications': typeof appLayoutCertificationsRoute;
    '/harvests': typeof appLayoutHarvestsRoute;
    '/invoicing': typeof appLayoutInvoicingRoute;
    '/licenses': typeof appLayoutLicensesRoute;
    '/vineyards': typeof appLayoutVineyardsRoute;
    '/signin': typeof authLayoutSigninRoute;
    '/vineyards/$vineyardId': typeof appLayoutVineyardsVineyardIdRoute;
}

export interface FileRoutesByTo {
    '/': typeof appLayoutIndexRoute;
    '/analysis': typeof appLayoutAnalysisRoute;
    '/cellar': typeof appLayoutCellarRoute;
    '/certifications': typeof appLayoutCertificationsRoute;
    '/harvests': typeof appLayoutHarvestsRoute;
    '/invoicing': typeof appLayoutInvoicingRoute;
    '/licenses': typeof appLayoutLicensesRoute;
    '/vineyards': typeof appLayoutVineyardsRoute;
    '/signin': typeof authLayoutSigninRoute;
    '/vineyards/$vineyardId': typeof appLayoutVineyardsVineyardIdRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/(app)': typeof appRouteWithChildren;
    '/(app)/_layout': typeof appLayoutRouteWithChildren;
    '/(auth)': typeof authRouteWithChildren;
    '/(auth)/_layout': typeof authLayoutRouteWithChildren;
    '/(app)/_layout/analysis': typeof appLayoutAnalysisRoute;
    '/(app)/_layout/cellar': typeof appLayoutCellarRoute;
    '/(app)/_layout/certifications': typeof appLayoutCertificationsRoute;
    '/(app)/_layout/harvests': typeof appLayoutHarvestsRoute;
    '/(app)/_layout/invoicing': typeof appLayoutInvoicingRoute;
    '/(app)/_layout/licenses': typeof appLayoutLicensesRoute;
    '/(app)/_layout/vineyards': typeof appLayoutVineyardsRoute;
    '/(auth)/_layout/signin': typeof authLayoutSigninRoute;
    '/(app)/_layout/': typeof appLayoutIndexRoute;
    '/(app)/_layout/vineyards_/$vineyardId': typeof appLayoutVineyardsVineyardIdRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/analysis'
        | '/cellar'
        | '/certifications'
        | '/harvests'
        | '/invoicing'
        | '/licenses'
        | '/vineyards'
        | '/signin'
        | '/vineyards/$vineyardId';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/'
        | '/analysis'
        | '/cellar'
        | '/certifications'
        | '/harvests'
        | '/invoicing'
        | '/licenses'
        | '/vineyards'
        | '/signin'
        | '/vineyards/$vineyardId';
    id:
        | '__root__'
        | '/(app)'
        | '/(app)/_layout'
        | '/(auth)'
        | '/(auth)/_layout'
        | '/(app)/_layout/analysis'
        | '/(app)/_layout/cellar'
        | '/(app)/_layout/certifications'
        | '/(app)/_layout/harvests'
        | '/(app)/_layout/invoicing'
        | '/(app)/_layout/licenses'
        | '/(app)/_layout/vineyards'
        | '/(auth)/_layout/signin'
        | '/(app)/_layout/'
        | '/(app)/_layout/vineyards_/$vineyardId';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    appRoute: typeof appRouteWithChildren;
    authRoute: typeof authRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
    appRoute: appRouteWithChildren,
    authRoute: authRouteWithChildren,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(auth)"
      ]
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_layout"
      ]
    },
    "/(app)/_layout": {
      "filePath": "(app)/_layout.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_layout/analysis",
        "/(app)/_layout/cellar",
        "/(app)/_layout/certifications",
        "/(app)/_layout/harvests",
        "/(app)/_layout/invoicing",
        "/(app)/_layout/licenses",
        "/(app)/_layout/vineyards",
        "/(app)/_layout/",
        "/(app)/_layout/vineyards_/$vineyardId"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_layout"
      ]
    },
    "/(auth)/_layout": {
      "filePath": "(auth)/_layout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_layout/signin"
      ]
    },
    "/(app)/_layout/analysis": {
      "filePath": "(app)/_layout.analysis.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/cellar": {
      "filePath": "(app)/_layout.cellar.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/certifications": {
      "filePath": "(app)/_layout.certifications.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/harvests": {
      "filePath": "(app)/_layout.harvests.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/invoicing": {
      "filePath": "(app)/_layout.invoicing.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/licenses": {
      "filePath": "(app)/_layout.licenses.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/vineyards": {
      "filePath": "(app)/_layout.vineyards.tsx",
      "parent": "/(app)/_layout"
    },
    "/(auth)/_layout/signin": {
      "filePath": "(auth)/_layout.signin.tsx",
      "parent": "/(auth)/_layout"
    },
    "/(app)/_layout/": {
      "filePath": "(app)/_layout.index.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/vineyards_/$vineyardId": {
      "filePath": "(app)/_layout.vineyards_.$vineyardId.tsx",
      "parent": "/(app)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
