// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"time"

	"github.com/google/uuid"
)

type Harvest struct {
	ID                int32
	GrapeVariety      string
	QuantityCollected string
	QualityNotes      string
	HarvestDate       time.Time
	CreatedAt         time.Time
	UserID            uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
}
