[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

diesel = { version = "2.2.6", features = ["postgres", "r2d2"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15.7"
