[workspace]
resolver = "1"
members = [
    "api",
    "domain",
    "infrastructure",
    "application",
    "shared",
]

[patch.crates-io]
traitobject = { git = "https://github.com/reem/rust-traitobject", rev = "b3471a15917b2caf5a8b27debb0b4b390fc6634f" }
